#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pyxdg
Version  : 0.26
Release  : 6
URL      : http://pypi.debian.net/pyxdg/pyxdg-0.26.tar.gz
Source0  : http://pypi.debian.net/pyxdg/pyxdg-0.26.tar.gz
Summary  : PyXDG contains implementations of freedesktop.org standards in python.
Group    : Development/Tools
License  : LGPL-2.0
Requires: pyxdg-python3
Requires: pyxdg-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
The XDG Package contains:
- Implementation of the XDG-Base-Directory Standard
http://standards.freedesktop.org/basedir-spec/

%package python
Summary: python components for the pyxdg package.
Group: Default
Requires: pyxdg-python3

%description python
python components for the pyxdg package.


%package python3
Summary: python3 components for the pyxdg package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pyxdg package.


%prep
%setup -q -n pyxdg-0.26

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1517678508
export CFLAGS="$CFLAGS -fstack-protector-strong "
export FCFLAGS="$CFLAGS -fstack-protector-strong "
export FFLAGS="$CFLAGS -fstack-protector-strong "
export CXXFLAGS="$CXXFLAGS -fstack-protector-strong "
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
