#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xAF88B3AC5DECB224 (thomas@kluyver.me.uk)
#
Name     : pyxdg
Version  : 0.25
Release  : 2
URL      : http://pypi.debian.net/pyxdg/pyxdg-0.25.tar.gz
Source0  : http://pypi.debian.net/pyxdg/pyxdg-0.25.tar.gz
Source99 : http://pypi.debian.net/pyxdg/pyxdg-0.25.tar.gz.asc
Summary  : PyXDG contains implementations of freedesktop.org standards in python.
Group    : Development/Tools
License  : LGPL-2.0
Requires: pyxdg-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
Patch1: CVE-2014-1624.patch

%description
The XDG Package contains:
- Implementation of the XDG-Base-Directory Standard
http://standards.freedesktop.org/basedir-spec/

%package python
Summary: python components for the pyxdg package.
Group: Default

%description python
python components for the pyxdg package.


%prep
%setup -q -n pyxdg-0.25
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1503671265
export CFLAGS="$CFLAGS -fstack-protector-strong "
export FCFLAGS="$CFLAGS -fstack-protector-strong "
export FFLAGS="$CFLAGS -fstack-protector-strong "
export CXXFLAGS="$CXXFLAGS -fstack-protector-strong "
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1503671265
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
